game/shared/tf/tf_weapon_bat.cpp
game/shared/tf/tf_weapon_bat.h

> * Long-range ball impacts no longer remove the victim's ability to fire their weapon but the victim is still slowed.
> * Max range balls now do 50% increased damage from a base of 15.
> * The flight time required to trigger the max effect has been reduced by 20%.
> * Ball regeneration time reduced to 10 seconds.

update sandman attributes

---

game/client/tf/tf_hud_mainmenuoverride.cpp

as "new user forums" no longer exist.

Actually point to tf2 forums

---

game/shared/tf/tf_gamerules.cpp
game/shared/tf/tf_gamerules.h

controlled by a new cvar: `mp_chat_clean_text`
this prevents users from disrupting the chat box by sending messages that contain newline characters (which is only possible with cheats)
cr and lf characters are replaced with question marks
this also replaces "mean spaces" like zero-width spaces with regular spaces (though im not sure if this feature is necessary or desirable)

prevent newlines from being sent in chat

---

game/server/player_lagcompensation.cpp

Clamping that convar prevents from abusing "Fake latency" commonly used by cheaters by hooking SendDatagram and AddLatencyToNetchan.

Clamp sv_maxunlag ConVar

---

bitmap/float_bm4.cpp
raytrace/raytrace.cpp

The raytracing code has debug variable `n_intersection_calculations`. This was used solely for debugging, but its existence caused a massive bottleneck in VRAD; performance nearly doubles on some systems without it.
More information and some performance testing can be found here: https://github.com/ValveSoftware/source-sdk-2013/pull/436

VRAD: Fix thread-sharing bug

---

engine/sv_main.cpp

This brings back Hor+ for 16:9> aspect ratios in fullscreen like in vanilla TF2.

Revert sv_restrict_aspect_ratio_fov back to 1

---

README.md

#295 and #296 
The warning was added as a note and disabling steam sync as an extra step
While the warning should stay, the extra step is a short term arrangement to prevent confusion while a better way of handling the problem is created. Please, discuss long term options like the ones mentioned in the open issues
alternatives are cited in #295 and #296

Basic Installation Instrucions Improvements: warning about custom/tc2 and instructions to disable steam sync

---

game/shared/tf/tf_gamemovement.cpp

This allows servers to restore the original functionality with a value of '10.0f' (or whatever other value they desire)
N/A
Adds a ternary check for TF_COND_BURNING with the two convar values as the true/false conditions. This matches the implementation
N/A
- [Y] This PR targets the `master` branch.
- [N] This change has been filed as an issue.
- [Y] No other PRs address this.
- [Y] This PR is as minimal as possible.
- [?] This PR does not introduce any regressions.
- [N] This PR has been tested on all platforms, on both a dedicated server and on a listen server.
Untested on any platforms, but this is exactly what the `CTFGameMovement::FullWalkMove` method did in ~Sept. 2015.
Server operators may not know that '10.0f' is the value to use to get the old behavior and there's no good way to …

Restore functionality to tf_parachute_maxspeed_onfire_z but set its value to match tf_parachute_maxspeed_z

---

creategameprojects.bat
creategameprojects_debug.bat
creategameprojects_dev.bat
download_libs.bat

Reduces console spam (`Press any key to continue . . . `) and stops AppVeyor (and possibly other CI) from hanging.

.bat: Don't pause on CI

---

materialsystem/shaderapidx9/shaderdevicedx8.cpp
materialsystem/shaderapidx9/shaderdevicedx8.h

N/A
This PR puts `#ifndef DX_TO_GL_ABSTRACTION` around new d3d9ex function usages, because d3d9ex functions are not implemented in ToGL, which causes builds to error on platforms that use ToGL (linux, macos).
| Windows | Should not affect | N/A | N/A    |
|   Linux | Built | N/A | `5.8.10-lqx1-1-lqx #1 ZEN SMP PREEMPT Thu, 17 Sep 2020 14:35:33 +0000` |
|  Mac OS | Unavailable | N/A | N/A      |
ToGL platforms will not be able to enjoy dx9ex optimizations.
Implement dx9ex into ToGL.

Fix DX9ex usage on ToGL

---

download_libs_linux.sh
download_libs_mac.sh

download_libs_linux/mac.sh now use the same arguments as download_libs.bat for consistency.
I was thinking of adding `-C -` so libs don't needlessly get redownloaded and interrupted downloads are resumable, but I'm not sure if it verifies files or not, and corrupt or outdated libs would have to be deleted manually.

download_libs: Consistency

---

devtools/makefile_base_posix.mak

N/A
The base `CXXFLAGS` has `-std=c++11` set. This PR changes it to `-std=c++17`.
| Windows | N/A | N/A | N/A    |
|   Linux | Built | Built | `5.8.10-lqx1-1-lqx #1 ZEN SMP PREEMPT Thu, 17 Sep 2020 14:35:33 +0000` |
|  Mac OS | N/A | N/A | N/A |
New/added C++ code will have to be C++17 compliant. (Already required anyways)
Revert to c++11

Switch to C++17 in Linux base Makefile

---

game/shared/econ/econ_item_description.cpp

None
Since before the Jungle Inferno update, there was a visual bug that affected localized item quality names. A hardcoded space was introduced and being part of the STS team, I talked to my colleagues which confirmed to me that this bug existed since 2015 or so. You can see here an screenshot of how it looks like:
As you can see, there is an extra space in the quality name of the item, and it's not a problem specific to this language as it was noticed in other languages too.
This PR fixes this issue.
|   Linux | Built and tested| N/A | `5.8.12-arch1-1 #1 …

Fix hardcoded space on localized quality names

---

game/shared/movevars_shared.cpp

#387 
Removing various #ifdefs
| Windows | Built, Tested | Built | Windows 10 |
None
None

Unlock various CS only cvars

---

game/shared/tf/tf_weapon_flamethrower.cpp
game/shared/tf/tf_weaponbase.cpp

for both tf2 and tc2, the server performs lag compensation for every time a flame particle is released
this doesn't actually help with lag at all, so it's an absolutely pointless waste of time for the server to do
this can be confirmed by using the sv_showlagcompensation cvar in a listen server
all lag compensation functions removed from the flamethrower's primaryattack function
||Client|Server|Version|
|-|:-:|:-:|-|
|Windows|no|no||
|Linux|yes|yes|5.8.0-1-amd64 #1 SMP Debian 5.8.7-1 (2020-09-05)|
|Mac OS|no|no||

remove flamethrower lag compensation

---

game/shared/tf/tf_player_shared.cpp

This changes the requirements for a given class/player to air dash:
Halloween Speed Boost condition allows air dash at all times for any class (unchanged)
All classes may air dash if they have nonzero air dash count
Scouts have base air dash count dictated by tf_scout_air_dash_count, other classes have 0
set_scout_doublejump_disabled attribute nullifies the effect of tf_scout_air_dash_count
Soda Popper Hype adds 4 to air dash count
air_dash_count attribute further adds to air dash count, increasing the number of dashes available
Differences from current:
set_scout_doublejump_disabled previously disabled air dashes entirely unless the player had Halloween Speed Boost or Soda Popper Hype, now it only disables the base air dash count that Scouts get
Soda Popper and the air_dash_count …

Rework CTFPlayer::CanAirDash (double jumps)

---

game/client/tf/hud_basedeathnotice.h
game/client/tf/tf_hud_deathnotice.cpp
game/server/tf/tf_projectile_arrow.cpp
game/server/tf/tf_projectile_flare.cpp
game/shared/tf/tf_gamerules.cpp
game/shared/tf/tf_weapon_bat.cpp
game/shared/tf/tf_weapon_bat.h
game/shared/tf/tf_weapon_jar.cpp

fixes the following bugs from the official tf2 wiki:
* [Sandman](https://wiki.teamfortress.com/wiki/Sandman#Bugs): When an enemy Pyro blasts the ball and it hits a friendly player, they are slowed, but are not damaged by it. 
* [Wrap Assassin](https://wiki.teamfortress.com/wiki/Wrap_Assassin#Bugs): If a player is hit by a friendly Scout's ornament that was deflected by an enemy Pyro, that player will not be inflicted with bleeding, even though the bleed icon and visual effects appear on the HUD and the screen respectively.
* [Rescue Ranger](https://wiki.teamfortress.com/wiki/Rescue_Ranger#Bugs): Reflected bolts from Pyros do not heal buildings.
* [Scorch Shot](https://wiki.teamfortress.com/wiki/Compression_blast#Bugs): Reflected flares from the Scorch Shot will not inflict radius damage …

fix various airblast projectile bugs

---

game/shared/gamemovement.cpp
game/shared/tf/tf_gamemovement.cpp

This pr fixes an issue with being stopped dead/momentum cancelled when surfing onto a new slope by adding an additional check to see if the player's predicted z velocity off the slope is still high enough to be considered above ground.
The code for this is ported from the `groundfix` sourcemod plugin by jayessZA and pancakelarry, which is used for jump.tf servers. More detailed explanation of the plugin & underlying bug can be found on [the discussion topic](https://jump.tf/forum/index.php/topic,2394.0.html) for it on jump.tf.
N/A
| Windows | Tested | Built | Windows 10 |
| …

Fix slope bug w/ surf maps

---

.github/README.md

#464
include "and `tf/addons` folders if you have them" in place of "folders"
The user now has to check for the existanse of 2 folders instead of 1, requiring double the braincells
adding this as a second bullet point under "* Do *not* delete the entire `tf/cfg` folder!", however it seemed exceedingly verbose.

Include `tf/addons` as a folder that has to be deleted

---

public/bspfile.h
public/filesystem_passthru.h
public/tier0/tslist.h
public/tier1/convar.h
public/tier1/strtools.h
tier0/memdbg.cpp
tier0/stacktools.cpp
tier0/threadtools.cpp
tier1/KeyValues.cpp
tier1/checksum_sha1.cpp
tier1/commandbuffer.cpp
tier1/strtools.cpp
tier1/strtools_unicode.cpp
tier1/utlbuffer.cpp
tier2/keyvaluesmacros.cpp

* None
Just PVS-Studio static analyzer warning fixes. 
Secure memory clean function `V_SecureClean` based on idea from https://git.openssl.org/?p=openssl.git;a=blob;f=crypto/mem_clr.c, but i'm not sure it should be mentioned here, because it is just idea, not implementation.
Product page: https://www.viva64.com/en/pvs-studio/
How to use for free: https://www.viva64.com/en/b/0600/
None
Not known.
Not known.

PVS-Studio analyzer warning fixes

---

game/client/c_soundscape.cpp
game/shared/SoundEmitterSystem.cpp
game_clean/copy/tf/gameinfo.txt

https://github.com/ValveSoftware/Source-1-Games/issues/2701
#468 
* Loads a soundscape named "scripts/soundscape_embed.txt" from within a workshop BSP, only if soundscape_fullmapname.txt is not present
* Loads a level sounds file named "maps/embed_level_sounds.txt" from within the workshop BSP, only if fullmapname_level_sounds.txt is not present
* Creates a new GAME search path in the TF2 workshop folder
* Note that the embedded file handling matches the implementation used for nav files already
Considering …

Fix issues with workshop soundscapes/soundscripts/embedded sounds

---

game/client/tf/tf_hud_building_status.cpp
game/server/tf/tf_obj.cpp
game/shared/tf/tf_player_shared.cpp

(if the relevant attribute is present)
This also corrects an issue where a disposable sentry would not be a minisentry if the player's melee weapon was not a wrench/gunslinger (normally, all disposable sentries are also minisentries).
N/A
Removes the GameModeUsesUpgrades checks from places that involve Disposable sentry code and instead strictly relies on the presence of the engy_disposable_sentry attribute.
I need some help testing this if possible.

Allow disposable sentries to be used outside MVM

---

game/server/tf/tf_player.cpp
game/server/tf/tf_player.h
game/shared/tf/tf_gamemovement.cpp
game/shared/tf/tf_quest_restriction.cpp
game/shared/tf/tf_weapon_shotgun.cpp

This increases the number of times self-knockback may be applied via the attribute.
This also changes m_bScattergunJump to m_iScattergunJump and updates any relevant code accordingly.
N/A
Changes CTFPlayer's m_bScattergunJump to int m_iScattergunJump.
Changes CTFScattergun's HasKnockback method to return true for values > 0 rather than only value 1.
Changes CTFScatterGun's FireBullet knockback logic to compare the value of m_iScattergunJump to the attribute value in order to determine whether to apply self-knockback.
I need some help testing this as my current setup can't... do anything.
|---------|:-----------------------------:|:-----------------------------:|------------------------ …

Allow set_scattergun_has_knockback attribute to take on values greater than 1
